language: php

sudo: false

php:
    - 7.2
    - 7.3
    - 8.0

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - COVERAGE=0
    matrix:
        - LARAVEL='6.*' TESTBENCH='4.*'
        - LARAVEL='7.*' TESTBENCH='5.*'
        - LARAVEL='8.*' TESTBENCH='6.*'

matrix:
    fast_finish: true
    exclude:
        - php: 7.1
          env: LARAVEL='6.*' TESTBENCH='4.*'

before_script:
    - composer config discard-changes true

before_install:
    - travis_retry composer self-update
    - travis_retry composer require "illuminate/support:${LARAVEL}" "illuminate/database:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update

install:
    - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
    - composer validate --strict
    - find src/ tests/ /config -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 php -l
    - vendor/bin/phpunit